name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run Unit Tests
      run: dotnet test BugsIncluded.Tests/BugsIncluded.Tests.csproj /p:CollectCoverage=true
    - name: Dotnet Publish Build Artifacts
      run: dotnet publish -c Release -r linux-arm -o webapp
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: webapp
        path:  webapp 
