name: Build & Deploy
on: 
  [push]:
    branches: 
      - master
  [pull_request]:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish Build Artifacts
      run:  dotnet publish -c Release -r linux-arm -o webapp --self-contained false
    - name: Copy Artifact Files to Webserver using SCP
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USERNAME: ${{ secrets.SERVER_USER }}
        PORT: ${{ secrets.SERVER_PORT }}
        KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
      with:
        source: "/home/runner/work/BugsIncluded/BugsIncluded/webapp/"
        target: "/usr/dotnetapps/"
    - name: Deploy Artifacts on Webserver using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          sudo rm -rf /usr/dotnetapps/bugsincluded_backup.tar.gz || true
          sudo systemctl stop bugsincluded.service
          sudo tar -czvf /usr/dotnetapps/backup.tar.gz -C /usr/dotnetapps/bugsincluded/ .
          sudo mv /usr/dotnetapps/bugsincluded/ /usr/dotnetapps/temp/
          sudo mkdir /usr/dotnetapps/bugsincluded/
          sudo mv /usr/dotnetapps/temp/*.db* /usr/dotnetapps/bugsincluded/
          sudo mv -v /usr/dotnetapps/github/workspace/webapp/* /usr/dotnetapps/bugsincluded/
          sudo rm -rf /usr/dotnetapps/github
          sudo rm -rf /usr/dotnetapps/temp
          sudo chmod -R 777 /usr/dotnetapps
          sudo systemctl restart bugsincluded.service
